services:
  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: mysecretpassword
      
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  monolite:
    image: monolite:latest
    build: 
      context: .
      dockerfile: ./backend/monolite/Dockerfile
      args:
        SERVICE_NAME: monolite
    container_name: spring_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/appdb
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
      FRONTEND_URL: http://localhost:3000
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: frontend:latest
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - monolite

volumes:
  postgres_data: