name: CD - Deploy Docker Images

on:
  workflow_run:
    workflows: ["CI - Build and Push Docker images"]
    branches: [ "main", "VR-8" ]
    types:
      - completed
  
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          GITHUB_SHA: ${{ github.event.workflow_run.head_sha }}
          DEPLOY_BRANCH: ${{ github.event.workflow_run.head_branch }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            SHA_TAG=${GITHUB_SHA::7}
            BRANCH=${GITHUB_REF_NAME}

            echo "Deploying branch: $BRANCH with SHA: $SHA_TAG"

            echo "${DOCKER_TOKEN}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

            cd ~/dev/CodePath

            git fetch origin
            git checkout -B $BRANCH origin/$BRANCH
            git pull origin $BRANCH

            sed -i "s/:latest/:$SHA_TAG/g" docker-compose.yaml

            docker compose pull
            docker compose up -d
