name: CD - Deploy Docker Images

on:
  push: 
    branches: [ "main", "VR-8" ]
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set Git SHA tag
        id: vars
        run: echo "SHA_TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          env:
            BRANCH: ${{ github.ref_name }}
          script: |
            SHA_TAG=${{ steps.vars.outputs.SHA_TAG }}
            BRANCH=${GITHUB_REF_NAME:-main}

            echo "Logging in to Docker Hub..."
            echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

            cd ~/dev/CodePath
            git fetch origin
            git checkout $BRANCH
            git pull origin $BRANCH

            sed -i "s/:latest/:$SHA_TAG/g" docker-compose.yaml

            docker compose pull
            docker compose up -d