name: CI - Build and Push Docker images

on:
  push:
    branches: [ "main", "VR-8" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #Build backend
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Build project
        working-directory: backend
        run: mvn clean package -DskipTests


      #Build frontend
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      #Docker Hub
      - name: Login in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
        
      - name: Build and push backend
        run: |
          SHA_TAG=${GITHUB_SHA::7}
          BACKEND_SERVICES=$(find backend -mindepth 1 -maxdepth 1 -type d -exec test -f '{}/Dockerfile' \; -print)

          for SERVICE in $BACKEND_SERVICES; do
            SERVICE_NAME=$(basename $SERVICE)
            echo "Building backend service: $SERVICE_NAME"
            
            docker build -f $SERVICE/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/$SERVICE_NAME:$SHA_TAG $SERVICE
            docker push ${{ secrets.DOCKER_USERNAME }}/$SERVICE_NAME:$SHA_TAG

            docker tag ${{ secrets.DOCKER_USERNAME }}/$SERVICE_NAME:$SHA_TAG \
                       ${{ secrets.DOCKER_USERNAME }}/$SERVICE_NAME:latest
            docker push ${{ secrets.DOCKER_USERNAME }}/$SERVICE_NAME:latest
          done
      
      - name: Build and push frontend
        run: |
          SHA_TAG=${GITHUB_SHA::7}

          echo "Building frontend"
          docker build -f frontend/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/frontend:$SHA_TAG frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:$SHA_TAG

          docker tag ${{ secrets.DOCKER_USERNAME }}/frontend:$SHA_TAG \
                     ${{ secrets.DOCKER_USERNAME }}/frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

  deploy:
    needs: build-and-push
    uses: ./.github/workflows/cd.yml
    with:
      branch: ${{ github.ref_name }}
      sha: ${{ github.sha }}
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  